First start by converting the array into a √m * √m matrix (The root should be rounded up). Next pad the 2D array with a number (1 value higher than the biggest element), as seen below. 

In [11]:
import math
import numpy as np
arr1 = [13,1,90,67, 42]

def larrySort(list):
    result = []
    sizeOfArray = len(list)
    roundedSquareRoot = math.ceil(sizeOfArray ** 0.5)
    start = 0
    end = roundedSquareRoot
    maxNum = max(list)
    paddedResult = []
    for i in range(roundedSquareRoot):
        result.append(arr1[start:end])
        start += roundedSquareRoot
        end += roundedSquareRoot
        if(len(result[i]) != roundedSquareRoot):
            x = np.pad(result[i], (0,roundedSquareRoot-len(result[i])), 'constant',constant_values = maxNum+1)
        else:
            x = result[i]
            
        paddedResult.append(x)
    
    return np.array(paddedResult)

print(larrySort(arr1))
    

[[13.  1. 90.]
 [67. 42. 91.]
 [91. 91. 91.]]


Sort the values by row. If the row is even, then sort in ascending order but if the row is odd, then sort in descending order, as seen below. 

In [12]:
def horizontalSort(result):
        for j in range(len(result)):
            temp = []
            if(j % 2 == 0):
                result[j].sort()
            else:
                result[j].sort()
                result[j] = result[j][::-1]
            
        return result    

print(horizontalSort(larrySort(arr1)))

[[ 1. 13. 90.]
 [91. 67. 42.]
 [91. 91. 91.]]


Then sort all columns in ascending order. 

In [13]:
def verticalSort(result):
    counter = 0 
    temp = []
    for k in range(len(result)):
        temp2 = []
        for l in range(len(result)):
            temp2.append(result[l][k])
            temp2 = sorted(temp2)
        temp.append(temp2)
        
    return np.transpose(np.array(temp))

print(verticalSort(horizontalSort(larrySort(arr1))))

[[ 1. 13. 42.]
 [91. 67. 90.]
 [91. 91. 91.]]


Then repeat the process √m + 1 times

In [14]:
def realLarrySort(result):
    result = larrySort(result)
    for i in range(len(result) + 1):
         result = verticalSort(horizontalSort(result))
    
    return result
    
print(realLarrySort(arr1))
    
    

[[ 1. 13. 42.]
 [91. 90. 67.]
 [91. 91. 91.]]


Then walk the grid to obtain the sorted array

In [15]:
def presentResult(result):
    maxElement = max(result)
    result = realLarrySort(result)
    for i in range(len(result)):
        if (i % 2 == 0):
            result[i] = result[i]
        else:
            result[i] = result[i][::-1]
            
    result = result.flatten(order='C')
    temp = []
    for j in range(len(result)):
        if (result[j] != (maxElement+1)):
            temp.append(result[j])
    
    return temp

print(presentResult(arr1))

[1.0, 13.0, 42.0, 67.0, 90.0]


One thing to note as seen above, the results sometimes are converted to floating point values using my implementation but that can be fixed with a quick conversion to integer values. That is an issue that I will have to look into.